### ISSUE TITLE
How to update k3s version ? 

### ISSUE THREAD

**Issue by mikekuzak** [jsiebens/k3s-on-gcp#1]
Hi 

I see you are using the CLI in the .sh to install K3s? Isn't there a TF provider to do this ? What about the RKE provider maybe, and how to you upgrade the version of K3s now via Terraform if this is running a shell install. 

```
curl -sfL https://get.k3s.io
``

**Comment by jsiebens** [comment]
Hi @mikekuzak,

This repository is not really intended for production usage, but more as an illustration of how it can be done.
I didn't know there is an RKE provider, but I will definitely have a look at it.
